### ISSUE TITLE
Bibliography style

### ISSUE THREAD

**Issue by janden** [mathieulagrange/paperStructureScene16#1]
Full names or first initials and last names? Latter might shorten a bit and could be more in line with most TASLP papers.

**Comment by mathieulagrange** [comment]
I spent some time to reach full name consistency ;) 

 suggest leaving it like this and move to option short if needed

**Comment by janden** [comment]
Ok we'll leave it now and see if we need space later..

**Comment by lostanlen** [comment]
I'm strongly in favor of trimming down the first names to their first initials.
For some reason I cannot see the bibliography when I compile the main TeX file from here.
