### ISSUE TITLE
"Colored" scene?

### ISSUE THREAD

**Issue by janden** [mathieulagrange/paperStructureScene16#10]
This is maybe beyond what we have time to do, but I'm putting this here just in case we do.

What about taking an auditory scene (represent as a scalogram), and label it according to the clusters found in the k-means step. Let's say we pick a small number of clusters (4). Can we identify the background vs. sound events that we're interested? Could be a fun motivating figure to put in the clustering section.

**Comment by mathieulagrange** [comment]
I agree, though in back and white this might be tricky. Let 's assign that to gregoire ;)

**Comment by janden** [comment]
Instead of colors, we can have a "track" below that indicates the current cluster (a-d) and have a legend somewhere.

**Comment by mathieulagrange** [comment]
good point

**Comment by mathieulagrange** [comment]
that being said, we need room for that in the paper if gregoire is willing to do it
