### ISSUE TITLE
Abbreviations?

### ISSUE THREAD

**Issue by janden** [mathieulagrange/paperStructureScene16#11]
Are the abbreviations ASC and ASSR very well-known? It feels more natural to write out "scene classification" or "scene similarity retrieval", but perhaps this is just personal preference.

**Comment by lostanlen** [comment]
The former is quite common (see e.g. Barchiesi 2014, Bisot 2016, Mafra 2016 and many others).
The latter has no precedent, which is not surprising since we are among the first to consider unsupervised classification of acoustic scenes.

**Comment by mathieulagrange** [comment]
Indeed, considering the fact that we only repeat them 3 three times in the whole manuscript I replaced the acronyms with the full wording
