### ISSUE TITLE
2013 results, supervised, late vs. early

### ISSUE THREAD

**Issue by gregoirelafay** [mathieulagrange/paperStructureScene16#14]
A) I managed to clean up the code and replicate all the results but one for the 2013 dataset (supervised : late/early ; mfcc/scattering/log-scattering).

I made a mistake when selecting the optimal parameters for "late, RBF, MFCCs" : 

68 ± 10 => 68 ± 14

B) Optimal Parameters

In the paper, to select the optimal parameters of the scattering and log-scattering settings (qth nearest neighbour for the RBF kernel), I look for the optimal parameters of the log-scattering settings, and use them for the scattering settings as well.

It was done on purpose, in order to ensure that only the "log" varies between the two scattering/log-scattering settings.

But now I'm thinking that it would be better to look for the optimal parameters of the **scattering** settings, and use them for the **log-scattering** ones. This way we clearly show that the log compression always improves the results of the scattering, regardless of the parameters optimization.

Here the new results : 

|                 | MFCCs         | Scattering     | Log-scattering |
| --- | --- | --- | --- |
| early, lin   | 0.54 (0.19)    | 0.62 (0.06)   |  0.66  (0.11)    |
| early, rbf  | 0.47 (0.16)    | 0.61 (0.09)   |   0.65   (0.06)  |
| late, lin    | 0.6  (0.09)     |  0.7   (0.08)  |    0.75   (0.05)  |
| late, rbf   | 0.68 (0.14)    | 0.73 (0.06)   | 0.77   (0.04)     |       

As you can see, it does not change the conclusions. 

BUT it does change the classification accuracies obtained over the five folds (see attached files)

[supervised_1.pdf](https://github.com/mathieulagrange/taslp16/files/659792/supervised_1.pdf)
[supervised_2.pdf](https://github.com/mathieulagrange/taslp16/files/659793/supervised_2.pdf)

We can no longer say that the "logarithmic compression provides a small, albeit consistent boost".

As we need to reduce the length of the paper, I propose the following :

1 - we use the new results, with optimal parameters learned on the **scattering** settings and used for the **log-scattering** settings as well.

2 - we remove all the results/interpretations/figures referring to the accuracies computed per fold.

What do you think ?

**Comment by mathieulagrange** [comment]
joakim is way for the day, so vincent please comment on it

**Comment by lostanlen** [comment]
Hi, there is no reason why scattering and log-scattering should be assigned the same SVM parameters.
The cross-validation for the two approaches should be done in parallel.
That said, I'm OK with removing Fig 3 which shows that the boost between scattering and log-scattering is more or less consistent across folds.

**Comment by mathieulagrange** [comment]
Well, that was our idea, too. But there seems to have been a discussion between gregoire and you or Joakim to study the impact of the log by freezing the parameters for the two approaches. Whatever we decide we have the data, so we can simply cut and paste

**Comment by mathieulagrange** [comment]
I am ok with both approaches so please decide vincent

**Comment by gregoirelafay** [comment]
FYI, the results if the parameters are optimized separately for scattering and log-scattering :  

|                 | MFCCs         | Scattering     | Log-scattering |
| --- | --- | --- | --- |
| early, lin   | 0.54 (0.19)    | 0.62 (0.06)   |  0.66  (0.11)    |
| early, rbf  | 0.47 (0.16)    | 0.61 (0.09)   |   **0.63   (0.06)**  |
| late, lin    | 0.6  (0.09)     |  0.7   (0.08)  |    0.75   (0.05)  |
| late, rbf   | 0.68 (0.14)    | 0.73 (0.06)   | **0.78   (0.06)**     |   

The modified values are in bold.

If we want to evaluate only the log compression effect, I think it makes sense to have the same SVM parameters for both scattering and log-scattering.

But I leave the decision to you. As you can see the results do not change the conclusions anyway.

**Comment by janden** [comment]
I agree with Vincent: we should show the parameters that are optimal for each system configuration. This is the most fair comparison.

**Comment by gregoirelafay** [comment]
ok done
