### ISSUE TITLE
Novelty of scattering transform features

### ISSUE THREAD

**Issue by janden** [mathieulagrange/paperStructureScene16#2]
In the introduction, we claim to demonstrate the usefulness of the scattering transform for extracting discriminative features. Now this has been done in other paper, so do we really want to put that here? Or do we mean something else?

**Comment by mathieulagrange** [comment]
Stating that we do here does not mean that you do not do it elsewhere. may be change demonstrate by show or confirm. Up to U.

The statement shall be repeated in the body with proper citation of the other studies.

**Comment by janden** [comment]
Ok sounds good. This was one of the things one of the reviewers was (sort of) getting at too. It really depends on the wording, like you say.
