### ISSUE TITLE
What if ?

### ISSUE THREAD

**Issue by mathieulagrange** [mathieulagrange/paperStructureScene16#8]
Re-reading the comments of rev 1: " The whole paper architecture is poor. " "The paper reads like a recipe for the specific task without justifications, insights or proofs of the different given definitions and statements."

I admit I have to agree...

now the paper effectively reads:
1:comp bio acoustics (which we do not do)
2:hierarchical model
3:unsupervised (for which the hierarchical model is good)
4:supervised (for which the hierarchical model is not good and the scattering not that great compared to the soa)
5: well, well

This does not spread a clear claim. So what if we would do this:

1: comp bio acoustics needs unsupervised analysis (but lack of data to evaluate such a tool)
2: hierarchical model (step1 scat, step 2 quantization)
3: experiments that validate step 1 (supervised setting, for which we show state of the art performance)
4: experiments that validate step 2 (unsupervised setting, plus supervised setting and a very nice discussion about the fact the quantization is likely to perform the same kind of selection that the svm is doing) (could test this with a knn may be bu that is another story).

As such the claim of the paper that should be repeated in the abstract, intro, conclusion is :+1: 

1 ASSR is needed for large scale unsupervised environmental data analysis, 
2 the commonly used  bag of frame approach fails
3 need for selectivity (like the one that the SVMs is doing in the supervised case)
4 that is the purpose of the quantization
5 it works well
6 and the fact that we do not see any gain of such a quantization step in the supervised case assert our claim (quantization helps to be more selective like the SVMs do)

**Comment by mathieulagrange** [comment]
This is a significant rewriting but I think this is worth it.

**Comment by janden** [comment]
I would tend to agree. The supervised section is quite weak. I would be ok even if we cut it out completely, but using it to motivate the use of the scattering transform as you suggest is better than the way we have it now.

That being said, it's a lot of work and there's not much time, especially since we need to factor in reviewing, polishing and so on. I think it would be worth it, though.

**Comment by janden** [comment]
Ok so first draft of the new version is in the reorg branch. Please let me know what you think. There's going to be a lot of polishing necessary but I think it's off to a good start.

If everyone is (more or less) ok with it, I will merge it into the master branch.
